name: Terraform AI BAU Patching

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  terraform-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest Terraform and AWS provider versions
        run: python scripts/fetch_latest_versions.py

      - name: Search for provider changes via DuckDuckGo
        run: python scripts/search_provider_changes.py

      - name: Analyze Terraform plan output with Claude AI
        run: python scripts/analyze_with_claude.py

      - name: Apply patches based on AI feedback
        run: python scripts/apply_patch.py

      - name: Commit and push changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add terraform-modules/
          git commit -m "chore: auto-patch terraform modules [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
